insert into Customer (name) values ('Emmery Kanwell');
insert into Customer (name) values ('Dolley Caffrey');
insert into Customer (name) values ('Una Pasby');
insert into Customer (name) values ('Debor McKeaveney');
insert into Customer (name) values ('Kristel Lothlorien');
insert into Customer (name) values ('Adi Fahrenbacher');
insert into Customer (name) values ('Elden Curm');
insert into Customer (name) values ('Nance Peppett');
insert into Customer (name) values ('Sena Dory');
insert into Customer (name) values ('Kelley Raithbie');
insert into Employee (name, phone_number, address) values ('Dotti Garrand', '8384120654', '3530 Tennyson Terrace');
insert into Employee (name, phone_number, address) values ('Rutledge Jakobsson', '4575528855', '19 Roth Parkway');
insert into Employee (name, phone_number, address) values ('Aurilia Hamerton', '2929220162', '2680 Dryden Alley');
insert into Employee (name, phone_number, address) values ('Annecorinne Wodeland', '1069430176', '8898 Eagle Crest Drive');
insert into Employee (name, phone_number, address) values ('Harlan Laboune', '7335027630', '9000 Kensington Parkway');
insert into Employee (name, phone_number, address) values ('Marissa Station', '8999497779', '751 Debs Crossing');
insert into Employee (name, phone_number, address) values ('Trude Hatcliffe', '7125104334', '94818 Farwell Road');
insert into Employee (name, phone_number, address) values ('Dorotea Cordobes', '6295397795', '076 Mallard Avenue');
insert into Employee (name, phone_number, address) values ('Hank Robottham', '9488553609', '3 Dixon Lane');
insert into Employee (name, phone_number, address) values ('Elvera Shorie', '8131996408', '27 Summer Ridge Road');
insert into Products (name, ingredients, description, price, available) values ('Tea', 'tea', 'Just a tea', 12, 9);
insert into Products (name, ingredients, description, price, available) values ('Coffe', 'coffe', 'Just black coffe', 14, 2);
insert into Products (name, ingredients, description, price, available) values ('White Cake', 'cake', 'Just white cake', 10, 8);
insert into Products (name, ingredients, description, price, available) values ('Blue Cake', 'cake', 'Just blue cake', 9, 10);
insert into Products (name, ingredients, description, price, available) values ('Green Cake', 'cake', 'Just gree cake', 10, 7);
insert into Products (name, ingredients, description, price, available) values ('Red Cake', 'cake', 'Just red cake', 9, 5);
insert into Products (name, ingredients, description, price, available) values ('White Cookies', 'cookies', 'Just white cookie', 14, 10);
insert into Products (name, ingredients, description, price, available) values ('Blue Cookies', 'cookies', 'Just blue cookie', 10, 1);
insert into Products (name, ingredients, description, price, available) values ('Red Cookies', 'cookies', 'Just red cookie', 11, 2);
insert into Products (name, ingredients, description, price, available) values ('Green Cookies', 'cookies', 'Just green cookie', 14, 10);
INSERT INTO `orders`(`id_p`, `status`, `id_e`, `id_c`) VALUES (1,"delivered",2,2);
INSERT INTO `orders`(`id_p`, `status`, `id_e`, `id_c`) VALUES (2,"delivered",2,1);
INSERT INTO `orders`(`id_p`, `status`, `id_e`, `id_c`) VALUES (4,"delivered",4,5);
INSERT INTO `orders`(`id_p`, `status`, `id_e`, `id_c`) VALUES (6,"undelivered",6,10);
INSERT INTO `orders`(`id_p`, `status`, `id_e`, `id_c`) VALUES (8,"delivered",8,4);
INSERT INTO `orders`(`id_p`, `status`, `id_e`, `id_c`) VALUES (1,"undelivered",1,6);
INSERT INTO `orders`(`id_p`, `status`, `id_e`, `id_c`) VALUES (3,"delivered",7,9);
INSERT INTO `orders`(`id_p`, `status`, `id_e`, `id_c`) VALUES (5,"delivered",10,8);
INSERT INTO `orders`(`id_p`, `status`, `id_e`, `id_c`) VALUES (7,"undelivered",9,3);
INSERT INTO `orders`(`id_p`, `status`, `id_e`, `id_c`) VALUES (9,"delivered",5,4);
CREATE VIEW `sales` AS select `cafe`.`products`.`name` AS `name` from (`cafe`.`orders` join `cafe`.`products` on((`cafe`.`orders`.`id_p` = `cafe`.`products`.`id`))) group by `cafe`.`orders`.`id_p`